master:
  image: trcook/rdockerhpc_master
  # build: ./docker/master
  links: 
    - redis
  volumes: 
    - ./data:/data

redis:
    image: redis
    container_name: redis
    ports: 
      - "6379:6379"


slave:
  image: trcook/rdockerhpc_slave
  # build: ./docker/slave
  links:
    - redis
  environment:
     - "affinity:container!=redis"