master:
  build: ./docker
  dockerfile: Dockerfile_master
  links: 
    - redis
  command: R
  volumes: 
    - ./data:/data

redis:
  image: redis
  container_name: redis

slave:
  build: ./docker
  dockerfile: Dockerfile_slave
  links:
    - redis