apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-svc
spec:
  ports:
    # the port that this service should serve on
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-svc
